// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoverLetter struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	CvID        pgtype.UUID        `json:"cv_id"`
	Content     string             `json:"content"`
	JobTitle    pgtype.Text        `json:"job_title"`
	CompanyName pgtype.Text        `json:"company_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GeneratedCv struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         string             `json:"user_id"`
	Name           string             `json:"name"`
	JobUrl         pgtype.Text        `json:"job_url"`
	JobTitle       pgtype.Text        `json:"job_title"`
	CompanyName    pgtype.Text        `json:"company_name"`
	JobDescription pgtype.Text        `json:"job_description"`
	CvData         []byte             `json:"cv_data"`
	MatchScore     pgtype.Int4        `json:"match_score"`
	AiSuggestions  []byte             `json:"ai_suggestions"`
	TemplateID     pgtype.Text        `json:"template_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type MasterProfile struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     string             `json:"user_id"`
	ResumeData []byte             `json:"resume_data"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type UserCredit struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               string             `json:"user_id"`
	FreeGenerationsUsed  int32              `json:"free_generations_used"`
	FreeGenerationsLimit int32              `json:"free_generations_limit"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
